---
title: Shop eXpresso
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
port: 4000
email: your-email@domain.com
description: applications pour gérer votre business.
markdown: kramdown
exclude:
- package.json
- node_modules
- gulpfile.js
